name-template: "v$NEXT_PATCH_VERSION"

tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: Breaking Changes
    label: breaking

  - title: Enhancements
    label: enhancement

  - title: Bug Fixes
    label: fix

  - title: Documentation
    label: documentation

  - title: Housekeeping
    label: housekeeping

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

no-changes-template: "- No changes"

template: |
  $CHANGES
