name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v1

  deploy:
    name: Deploy

    needs: test

    runs-on: ubuntu-latest

    if: >
      startsWith(github.ref, 'refs/tags/v') &&
      github.repository == 'arnohovhannisyan/jsonc-pragma'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
