name: Draft Release

on:
  push:
    branches:
      - master

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
